In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Original array:", arr1)
print("Type of the array:", type(arr1))
print("Shape of the array:", arr1.shape)

Original array: [1 2 3 4 5]
Type of the array: <class 'numpy.ndarray'>
Shape of the array: (5,)


In [3]:
#reshape to 2d
arr2 = arr1.reshape(1, 5)
print("Reshaped array:", arr2)

Reshaped array: [[1 2 3 4 5]]


In [6]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D array:", arr3)
print("Shape of the 2D array:", arr3.shape)

Original 2D array: [[1 2 3]
 [4 5 6]]
Shape of the 2D array: (2, 3)


In [7]:
arr4=np.arange(0,10,2)
print("Array with arange:", arr4)

Array with arange: [0 2 4 6 8]


In [8]:
#2d array of all 1
arr5=np.ones((2,3))
print("2D array of all ones:\n", arr5)

2D array of all ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#identity matrix
arr6=np.eye(3)
print("Identity matrix:\n", arr6)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8
